-- ============================================
-- Campus Nexus - MySQL Local Database Setup
-- Run this in MySQL Workbench or via command line:
--   mysql -u root -p < setup.sql
-- ============================================

CREATE DATABASE IF NOT EXISTS campus_nexus CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE campus_nexus;

-- 1. PROFILES TABLE
CREATE TABLE IF NOT EXISTS profiles (
  id VARCHAR(36) PRIMARY KEY,          -- UUID, generated by backend
  email VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL DEFAULT '',
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('student','teacher','hod','admin') NOT NULL DEFAULT 'student',
  department VARCHAR(255),
  phone VARCHAR(50),
  avatar_url TEXT,
  cgpa DECIMAL(4,2),
  skills TEXT,
  resume_url TEXT,
  portfolio_url TEXT,
  github_url TEXT,
  linkedin_url TEXT,
  profile_completion INT DEFAULT 20,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 2. JOBS TABLE
CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  company VARCHAR(255) NOT NULL,
  position VARCHAR(255) NOT NULL,
  description TEXT,
  location VARCHAR(255),
  package VARCHAR(100),
  requirements TEXT,
  min_cgpa DECIMAL(4,2) DEFAULT 0.00,
  allowed_departments VARCHAR(500),
  allowed_batches VARCHAR(255),
  status ENUM('active','closed','draft') NOT NULL DEFAULT 'active',
  deadline DATE,
  created_by VARCHAR(36),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL
);

-- 3. APPLICATIONS TABLE
CREATE TABLE IF NOT EXISTS applications (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  student_id VARCHAR(36) NOT NULL,
  job_id BIGINT NOT NULL,
  status ENUM('applied','shortlisted','selected','rejected') NOT NULL DEFAULT 'applied',
  applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_application (student_id, job_id),
  FOREIGN KEY (student_id) REFERENCES profiles(id) ON DELETE CASCADE,
  FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
);

-- 4. SAVED JOBS TABLE
CREATE TABLE IF NOT EXISTS saved_jobs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  student_id VARCHAR(36) NOT NULL,
  job_id BIGINT NOT NULL,
  saved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_saved_job (student_id, job_id),
  FOREIGN KEY (student_id) REFERENCES profiles(id) ON DELETE CASCADE,
  FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
);
